# Project: MBTI
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = MBTIRUN.o
LINKOBJ  = MBTIRUN.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW/mingw32/lib" -static-libgcc -lbgi -lgdi32 -lcomdlg32 -luuid -loleaut32 -lole32
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW/lib/gcc/mingw32/4.4.1/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW/lib/gcc/mingw32/4.4.1/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW/lib/gcc/mingw32/4.4.1/include/c++"
BIN      = MBTI.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

MBTIRUN.o: MBTIRUN.cpp
	$(CPP) -c MBTIRUN.cpp -o MBTIRUN.o $(CXXFLAGS)
